[package]
name = "work_report"
version = "0.1.0"
authors = ["Katsuya SUZUKI <syssec-diginnos>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.15"
glob = "0.3.0"
md5 = "0.7.0"
regex = "1.3.9"
